### ISSUE TITLE
Создатель данного ПО гей

### ISSUE THREAD

**Issue by opcodeIII** [1member1/lzt_vk#1]
Прошу его поправить проблему. Ее легко убрать,если автор убьетса нахуй.

Логи ПО не прилагаю.

**Comment by opcodeIII** [comment]
Мда,игнор минута. Автор ЧСВ

**Comment by 1member1** [comment]
Здравствуйте, вы перепутали репозитории, для данной ошибки необходимо создать issues в одном из репозиторий данного пользователя https://github.com/n4f3d9/

**Comment by opcodeIII** [comment]
Нет,это вы что-то перепутали!

**Comment by 1member1** [comment]
нет
